name: 'Build Remède android application'

on:
  push:
    branches:
      - dev

jobs:
  build-android:
    permissions:
      contents: write
    runs-on: 'ubuntu-latest'
    steps:
      - uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: app/android
          output-path: builds/remede.apk
          browserstack-upload: true
          ruby-version: "2.7.5"
          bundler-version: "2.3.26"
          fastlane-env: "debug"

      - name: Commit changes
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git config pull.rebase true
          git add builds/*
          git commit -m "chore(binaries): added latest Remède binaries"
          git pull

      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: 'dev'
