# This workflow uses actions that are not certified by GitHub.
# This workflow execute a python scripts to check if ressources are correctly formatted !

name: Ressources format

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  generation:
    name: Run ressources generation (wordlist, IPA list)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ressources generation
        run: python3 scripts/pre_generate_ressources.py
